default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mysuperuser2
  password: mysuperpass2
  host: localhost
  port: 5432

development:
  <<: *default
  database: new_test_guru

test:
  <<: *default
  database:

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database:
  username:
  password:
